//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_sableInputs_left_a;
        
        private static SteamVR_Action_Vector2 p_sableInputs_right_analog_stick;
        
        private static SteamVR_Action_Single p_sableInputs_right_trigger;
        
        private static SteamVR_Action_Boolean p_sableInputs_right_trigger_click;
        
        private static SteamVR_Action_Boolean p_sableInputs_right_analog_center;
        
        private static SteamVR_Action_Boolean p_sableInputs_left_grip_pressed;
        
        private static SteamVR_Action_Boolean p_sableInputs_right_grip_pressed;
        
        public static SteamVR_Action_Boolean sableInputs_left_a
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_left_a.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 sableInputs_right_analog_stick
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_right_analog_stick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single sableInputs_right_trigger
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_right_trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean sableInputs_right_trigger_click
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_right_trigger_click.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sableInputs_right_analog_center
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_right_analog_center.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sableInputs_left_grip_pressed
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_left_grip_pressed.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean sableInputs_right_grip_pressed
        {
            get
            {
                return SteamVR_Actions.p_sableInputs_right_grip_pressed.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.sableInputs_left_a,
                    SteamVR_Actions.sableInputs_right_analog_stick,
                    SteamVR_Actions.sableInputs_right_trigger,
                    SteamVR_Actions.sableInputs_right_trigger_click,
                    SteamVR_Actions.sableInputs_right_analog_center,
                    SteamVR_Actions.sableInputs_left_grip_pressed,
                    SteamVR_Actions.sableInputs_right_grip_pressed};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.sableInputs_left_a,
                    SteamVR_Actions.sableInputs_right_analog_stick,
                    SteamVR_Actions.sableInputs_right_trigger,
                    SteamVR_Actions.sableInputs_right_trigger_click,
                    SteamVR_Actions.sableInputs_right_analog_center,
                    SteamVR_Actions.sableInputs_left_grip_pressed,
                    SteamVR_Actions.sableInputs_right_grip_pressed};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.sableInputs_left_a,
                    SteamVR_Actions.sableInputs_right_trigger_click,
                    SteamVR_Actions.sableInputs_right_analog_center,
                    SteamVR_Actions.sableInputs_left_grip_pressed,
                    SteamVR_Actions.sableInputs_right_grip_pressed};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.sableInputs_right_trigger};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.sableInputs_right_analog_stick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.sableInputs_left_a,
                    SteamVR_Actions.sableInputs_right_analog_stick,
                    SteamVR_Actions.sableInputs_right_trigger,
                    SteamVR_Actions.sableInputs_right_trigger_click,
                    SteamVR_Actions.sableInputs_right_analog_center,
                    SteamVR_Actions.sableInputs_left_grip_pressed,
                    SteamVR_Actions.sableInputs_right_grip_pressed};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_sableInputs_left_a = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/SableInputs/in/left_a")));
            SteamVR_Actions.p_sableInputs_right_analog_stick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/SableInputs/in/right_analog_stick")));
            SteamVR_Actions.p_sableInputs_right_trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/SableInputs/in/right_trigger")));
            SteamVR_Actions.p_sableInputs_right_trigger_click = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/SableInputs/in/right_trigger_click")));
            SteamVR_Actions.p_sableInputs_right_analog_center = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/SableInputs/in/right_analog_center")));
            SteamVR_Actions.p_sableInputs_left_grip_pressed = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/SableInputs/in/left_grip_pressed")));
            SteamVR_Actions.p_sableInputs_right_grip_pressed = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/SableInputs/in/right_grip_pressed")));
        }
    }
}
