//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_SableInputs : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean left_a
        {
            get
            {
                return SteamVR_Actions.sableInputs_left_a;
            }
        }
        
        public virtual SteamVR_Action_Vector2 right_analog_stick
        {
            get
            {
                return SteamVR_Actions.sableInputs_right_analog_stick;
            }
        }
        
        public virtual SteamVR_Action_Single right_trigger
        {
            get
            {
                return SteamVR_Actions.sableInputs_right_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_trigger_click
        {
            get
            {
                return SteamVR_Actions.sableInputs_right_trigger_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_analog_center
        {
            get
            {
                return SteamVR_Actions.sableInputs_right_analog_center;
            }
        }
        
        public virtual SteamVR_Action_Boolean left_grip_pressed
        {
            get
            {
                return SteamVR_Actions.sableInputs_left_grip_pressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean right_grip_pressed
        {
            get
            {
                return SteamVR_Actions.sableInputs_right_grip_pressed;
            }
        }
    }
}
